name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 12 * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        laravel: [ 11, 12 ]
        stripe: [ 13, 14, 15, 16, 17 ]

    name: php v${{ matrix.php }} - Laravel v${{ matrix.laravel }} - Stripe v${{ matrix.stripe }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          ini-values: error_reporting=E_ALL
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --dev --no-update
          composer require "stripe/stripe-php=^${{ matrix.stripe }}"
          composer update --prefer-dist --no-interaction --no-progress
          composer show -D

      - name: Execute tests
        run: composer test:coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
